"""Markdown + dark-mode HTML brief renderer."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from jinja2 import Template

from vantage.models import ResearchBrief, Signal

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Vantage Brief – {{ brief.topic }}</title>
  <style>
    :root {
      --bg: #0d1117;
      --surface: #161b22;
      --border: #30363d;
      --text: #e6edf3;
      --muted: #8b949e;
      --accent: #58a6ff;
      --green: #3fb950;
      --orange: #d29922;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
      background: var(--bg);
      color: var(--text);
      line-height: 1.6;
      padding: 2rem 1rem;
    }
    .container { max-width: 820px; margin: 0 auto; }
    header {
      border-bottom: 1px solid var(--border);
      padding-bottom: 1.5rem;
      margin-bottom: 2rem;
    }
    h1 { font-size: 1.75rem; font-weight: 600; margin-bottom: 0.4rem; }
    .meta { color: var(--muted); font-size: 0.9rem; }
    .badge {
      display: inline-block;
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 999px;
      padding: 0.15rem 0.7rem;
      font-size: 0.75rem;
      margin-right: 0.4rem;
      color: var(--muted);
    }
    .summary {
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 8px;
      padding: 1.25rem;
      margin-bottom: 2rem;
      white-space: pre-wrap;
      font-size: 0.95rem;
    }
    h2 {
      font-size: 1.15rem;
      margin: 1.75rem 0 0.75rem;
      color: var(--accent);
    }
    .signal {
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 8px;
      padding: 1rem 1.2rem;
      margin-bottom: 0.75rem;
      transition: border-color 0.15s;
    }
    .signal:hover { border-color: var(--accent); }
    .signal a {
      color: var(--text);
      text-decoration: none;
      font-weight: 500;
    }
    .signal a:hover { color: var(--accent); }
    .signal .src {
      font-size: 0.75rem;
      text-transform: uppercase;
      letter-spacing: 0.04em;
      color: var(--muted);
      margin-bottom: 0.25rem;
    }
    .signal .metrics {
      font-size: 0.8rem;
      color: var(--green);
      margin-top: 0.35rem;
    }
    .snippet {
      color: var(--muted);
      font-size: 0.88rem;
      margin-top: 0.4rem;
      display: -webkit-box;
      -webkit-line-clamp: 2;
      -webkit-box-orient: vertical;
      overflow: hidden;
    }
    footer {
      margin-top: 3rem;
      padding-top: 1rem;
      border-top: 1px solid var(--border);
      color: var(--muted);
      font-size: 0.8rem;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>{{ brief.topic }}</h1>
      <div class="meta">
        Vantage research brief · {{ brief.generated_at.strftime("%Y-%m-%d %H:%M UTC") }} ·
        last {{ brief.days_covered }} days · {{ brief.total_signals }} signals collected
      </div>
      <div style="margin-top:0.75rem">
        {% for s in brief.sources_queried %}
          <span class="badge">{{ s }}</span>
        {% endfor %}
      </div>
    </header>

    <div class="summary">{{ brief.summary }}</div>

    {% if brief.key_themes %}
    <h2>Themes</h2>
    <p>
      {% for t in brief.key_themes %}
        <span class="badge">{{ t }}</span>
      {% endfor %}
    </p>
    {% endif %}

    <h2>Ranked signals</h2>
    {% for sig in brief.top_signals %}
    <div class="signal">
      <div class="src">{{ sig.source }}{% if sig.subreddit_or_repo %} · {{ sig.subreddit_or_repo }}{% endif %}</div>
      <a href="{{ sig.url }}" target="_blank" rel="noopener">{{ sig.title }}</a>
      {% if sig.snippet %}
      <div class="snippet">{{ sig.snippet }}</div>
      {% endif %}
      <div class="metrics">
        engagement {{ "%.0f"|format(sig.engagement) }}
        {% if sig.raw_metrics %}
          · {% for k, v in sig.raw_metrics.items() %}{{ k }}={{ v }}{% if not loop.last %}, {% endif %}{% endfor %}
        {% endif %}
        {% if sig.published_at %} · {{ sig.published_at.strftime("%Y-%m-%d") }}{% endif %}
      </div>
    </div>
    {% endfor %}

    <footer>
      Generated by <strong>Vantage</strong> – engagement-ranked social research.<br />
      No SEO. Real community attention only.
    </footer>
  </div>
</body>
</html>
"""


def to_markdown(brief: ResearchBrief) -> str:
    lines = [
        f"# Vantage Brief: {brief.topic}",
        "",
        f"*Generated {brief.generated_at.strftime('%Y-%m-%d %H:%M UTC')} · "
        f"last {brief.days_covered} days · {brief.total_signals} signals*",
        "",
        f"**Sources:** {', '.join(brief.sources_queried)}",
        "",
        "## Summary",
        "",
        brief.summary,
        "",
    ]
    if brief.key_themes:
        lines.append("## Themes")
        lines.append("")
        lines.append(", ".join(f"`{t}`" for t in brief.key_themes))
        lines.append("")

    lines.append("## Ranked signals")
    lines.append("")
    for i, s in enumerate(brief.top_signals, 1):
        metrics = ""
        if s.raw_metrics:
            metrics = " · " + ", ".join(f"{k}={v}" for k, v in s.raw_metrics.items())
        date = s.published_at.strftime("%Y-%m-%d") if s.published_at else ""
        lines.append(f"{i}. **[{s.title}]({s.url})** ({s.source}){metrics} {date}")
        if s.snippet:
            lines.append(f"   > {s.snippet[:200]}…")
        lines.append("")

    lines.append("---")
    lines.append("*Vantage – engagement-ranked social signals*")
    return "\n".join(lines)


def to_html(brief: ResearchBrief) -> str:
    tmpl = Template(HTML_TEMPLATE)
    return tmpl.render(brief=brief)


def save_brief(brief: ResearchBrief, out_dir: Path | str = ".") -> tuple[Path, Path]:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    safe = "".join(c if c.isalnum() or c in "-_" else "-" for c in brief.topic.lower())[:50].strip("-")
    ts = brief.generated_at.strftime("%Y%m%d-%H%M")
    md_path = out / f"vantage-{safe}-{ts}.md"
    html_path = out / f"vantage-{safe}-{ts}.html"

    md_path.write_text(to_markdown(brief), encoding="utf-8")
    html_path.write_text(to_html(brief), encoding="utf-8")

    brief.markdown_path = str(md_path)
    brief.html_path = str(html_path)
    return md_path, html_path
